language: php
php:
    - '5.4'
	- '5.5'
    - '5.6'
	- hhvm
	
services:
    - mysql
env:
  global:
    #Reply Email 
    - EMAIL='kevin@bt48.com'
before_script:
   - "mysql -e 'create database drupal_test;'"